### PR TITLE
Darian models

### PR DESCRIPTION
**Pull request by DarianRushworth**
###
Setup the Models and Seeders.
Defined relations:
* User to many Completed Exercises
* Exercises to many Completed Exercises
* User many to many Exercises through Completed Exercises

### CODE REVIEW

**Comment by DiegoOTdC** [comment]
I think it looks good! Great that you already added the content to the methods!

**Review by DiegoOTdC — CHANGES_REQUESTED** [review]
hide the postgres url?

**Review by DiegoOTdC — COMMENTED** [review]
Shouldn't ranking be an integer? instead of string?

**Comment by DarianRushworth** [comment]
Database Url Hidden. Great find.

**Review by DiegoOTdC — APPROVED** [review]

**Pull request merged**
