### PR TITLE
Darian quiz setup

### PR DESCRIPTION
**Pull request by DarianRushworth**
###
Set-up extra models, migrations and seeders
Along with new Routes and edited Router.
* Edited Route fro patching on completing level 2, total exp of the user increases.
* New models and Migrations for Quiz Questions and Completed Quizzes
* Minimal dummy-data for now, working on that shortly
* New Routes for fetching Quizzes questions and updating the Completed Quizzes, whilst updating the user's total exp.

### CODE REVIEW

**Comment by StephBerg86** [comment]
Looks good to me

**Review by DiegoOTdC — APPROVED** [review]
Looks really great man! You've done a lot ! 👍

**Review by StephBerg86 — APPROVED** [review]

**Comment by DarianRushworth** [comment]
All I did extra was add in the questions for the quiz, and reset the DB so the questions are now ready to be fetched.

**Review by DiegoOTdC — APPROVED** [review]
great!

**Pull request merged**
