### PR TITLE
Scaled down to one join table

### PR DESCRIPTION
**Pull request by DarianRushworth**
### 
We decided that there wasn't a need for a second join table, so we scaled down to a single join table with all
relevant data.

### CODE REVIEW

**Review by DiegoOTdC — COMMENTED** [review]
Just change the routers and everything is good to go! 👍

**Comment by DarianRushworth** [comment]
Router edit complete, was only on the patch request when the quiz has been completed.

**Review by DiegoOTdC — APPROVED** [review]
Looks great!

**Review by StephBerg86 — APPROVED** [review]
Good that you could scale it down to one. Looks more logical.

**Pull request merged**
